### ISSUE TITLE
Tracking issue: trusted functions in `creusot-contracts`

### ISSUE THREAD

**Issue by arnaudgolfouse** [creusot-rs/creusot#1192]
The following functions in `creusot-contracts` are still trusted, and it could certainly be removed:
- [ ] `logic::FSet::ext_eq`
- [ ] `std::iter::Iterator::map_inv`
- [ ] `std::slice::Iter::produces_refl`
- [ ] `std::slice::Iter::produces_trans`
- [ ] `std::vec::IntoIter::produces_trans`
- [ ] `std::iter::filter::Filter::produces_trans`
- [ ] `std::iter::fuse::Fuse::is_fused`
- [ ] `std::iter::map_inv::MapInv::produces_refl`
- [ ] `std::iter::map_inv::MapInv::produces_trans`
- [ ] `std::iter::map_inv::MapInv::preservation_inv`
- [ ] `std::iter::map_inv::MapInv::produces_one_invariant`
- [ ] `std::iter::map_inv::MapInv::produces_one`
- [ ] `std::iter::map::Map::produces_trans`
- [ ] `std::iter::skip::Skip::produces_trans`
- [ ] `std::iter::zip::Zip::produces_trans`

I'm not saying we should do this immediately, but it would be nice to eventually properly prove those functions.

**Comment by jhjourdan** [comment]
Fixed by #1635 .
