### ISSUE TITLE
Tracking Issue for Type Invariants

### ISSUE THREAD

**Issue by voidc** [creusot-rs/creusot#845]
This issue tracks the remaining work for type invariants:

- [x] #843 
- [x] Float quantifiers for invariants: #846 
- [ ] Always include user invariant: The user invariant should always be included and be substituted with the correct impl when a concrete clone is asked. 
- [x] Structural user invariants: allow `Vec<i32>` to be considered to have a trivial invariant.
- [ ] Structural invariants for closures and arrays #847

**Comment by jhjourdan** [comment]
All these points have been addressed in current master.
